# Generated by Django 4.2.3 on 2023-10-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.UUIDField()),
                ('commenter', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
    ]
