from django.urls import path
from . import views

urlpatterns = [
    path('',views.signin,name='signin'),
    path('home',views.index,name='index'),
    path('signin/index.html/home',views.index,name='index'),
    path('signin/index.html/index',views.index,name='index'),
    path('profile/index',views.index,name='index'),
    path('profile/profile-poster',views.profile_poster,name='profile_poster'),
    path('profile/profile',views.profile_poster,name='profile_poster'),
    path('signin/',views.signin,name="signin"),
    path('upload',views.upload,name="upload"),
    path('signin/index.html/upload',views.upload,name='upload'),
    path('likes',views.likes,name="likes"),
    path('delete_post',views.delete_post,name="delete_post"),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('signin/profile',views.profile,name='profile'),
    path('settings/profile',views.profile,name='profile'),
    path('signin/index.html/profile',views.profile,name='profile'),
    path('profile_poster',views.profile_poster,name='profile_poster'),
    path('signin/index.html/profile-poster',views.profile_poster,name='profile_poster'),
    path('signup/signin',views.signin,name='signin'),
    path('signup/signup',views.signup,name='signup'),
    path('signin/signup',views.signup,name='signup'),
    path('settings/',views.settings,name='settings'),
    path('signup/settings',views.settings,name='settings'),
    path('signin/settings',views.settings,name='settings'),
    path('profile/settings',views.settings,name='settings'),
    path('signin/signup/settings',views.settings,name='settings'),
    path('signup/signin/settings',views.settings,name='settings'),
    path('signin/index.html/settings',views.settings,name='settings'),
    path('signin/settings',views.settings,name='settings'),
    path('signin/index.html/',views.index,name='index'),
    path('signin/index.html/index.html',views.index,name='index'),
    path('signin/index.html/delete_post',views.delete_post,name='delete'),
    path('signin/index.html/follow',views.follow,name='follow'),
    path('profile/follow',views.follow,name='follow'),
    path('signin/index.html/logout',views.logout,name='logout'),
    path('profile/logout',views.logout,name='logout'),
    path('signin/index.html/post',views.post,name='post'),
    path('profile/post',views.post,name='post'),
    path('signin/index.html/comment',views.comment,name='comment'),
    path('profile/comment',views.comment,name='comment'),
]
